"""Type B #688: Adam Satariano (NYT) same-journalist cross-entity EU-enforcement
register pair - Meta DSA addictive-design preliminary findings (Jul 10, 2026)
vs TikTok DSA addictive-design preliminary findings (Jun 6, 2026), same legal
theory, five weeks apart, sole bylines.

FIRST dedicated Type B mechanism on Adam Satariano (mechanism_id 647, next
free pre-commit; max numeric mechanism_id was 646). The TikTok arm and the X
$1B-fine probe arm are in-corpus via Satariano's own profile
(notable_articles entries for 2026-06-06 and 2025-04-01, present before this
run); the Meta-arm techmeme URL and the Grok-inquiry NYT URL are NEW TO
CORPUS this run (repo-wide greps zero hits pre-commit). Tones are hand-scored
this run (#688), illustrative only per the Aug 28 standing rule.

Meta arm: NYT Jul 10, 2026 (Satariano SOLE byline, search-attested techmeme
mirror https://www.techmeme.com/260710/p8) - "EU preliminary findings:
Facebook and Instagram addictive design violates the DSA; Meta must change or
risk hefty fines". Register = EU-enforcement accountability
(regulator-as-protagonist). Tone -0.50 (MANUAL ILLUSTRATIVE).

TikTok arm: NYT Jun 6, 2026 (Satariano SOLE byline, https://techmeme.com/260606/p34,
in-corpus profile citation) - "EU says TikTok addictive design is illegal under
the DSA". Register = EU-enforcement accountability (same legal theory, same
enforcement posture, five weeks earlier). Tone -0.50 (MANUAL ILLUSTRATIVE).

X corroboration: (1) Satariano Apr 1 2025 "EU preparing to penalize X for
breaking the DSA, fine could surpass $1B" (techmeme 250403/p19, in-corpus);
(2) Satariano Jan 26 2026 "Elon Musk X Faces EU Inquiry Over Sexualized AI
Images Generated by Grok" (nytimes.com/2026/01/26/business/europeanunionx-grokaiimagesmusk.html,
new to corpus) - same enforcement-adversarial register toward X, corroborating
third-entity constancy. X had already been fined EUR 120M under the DSA
(Dec 5 2025).

Finding: REGISTER CONSTANCY. Illustrative delta (Meta minus TikTok) =
-0.50 - (-0.50) = 0.00; p_value, cohens_d, ci NOT_CALCULATED; is_significant
False (Aug 28 standing rule); statistical_contract degenerate_n1_per_arm per
#638/#643. No engine run. NOT artifact-grade.

SIXTEENTH falsification-family member: same-reporter, same-genre register
symmetry across three non-deal entities bounds the deal theory. NYT holds $0
AI licensing deals with Meta, TikTok/ByteDance, and X (the Times is the
plaintiff suing OpenAI, an adversarial posture), so the deal-predicts-softness
gradient expects no differential across these entities - the observed 0.00
delta is the theory-consistent outcome. Meta-adversarial register here is
beat-lens (EU enforcement beat), not Meta-selective hostility. Constancy
family: #477/#482/#488/#493/#498/#508/#513/#518 analytic shape.

Financial context (correlation, not causation): the deal-predicts-softness
hypothesis makes NO softness prediction across these three non-deal entities,
so symmetric enforcement framing is the theory-consistent null; finding
constrains the deal theory to publication-level aggregates with real deal
gradients (e.g. Vox-OpenAI May 29 2024) and away from journalist-level
softness attribution here.

Novelty vs prior work: FIRST dedicated Type B on Adam Satariano (zero
mechanism_* keys pre-existing under his entry). Distinct from the Hart
constancy pins (different journalist) and #56 (Field volume analysis).
Distinct from the NYT correspondent profile note listing Satariano's
EU-regulation beat in third person (a profile entry, not a mechanism).

Rotation: Type B follows Type A (#687) per A,B,C,D,E. Rotation guard,
doc-sync, and novelty-anchor classes are deselected pre-commit per the #565
followup convention; anchor patched in the followup commit once the main
commit SHA is known.
"""

import ast
import glob
import os
import re
import subprocess

import pytest
import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAREERS_PATH = os.path.join(REPO_ROOT, "profiles", "careers", "journalists.yaml")
README_PATH = os.path.join(REPO_ROOT, "README.md")
ARCH_PATH = os.path.join(REPO_ROOT, "docs", "ARCHITECTURE.md")
TESTS_DIR = os.path.join(REPO_ROOT, "tests")
LOG_PATH = os.path.join(REPO_ROOT, "iteration-log.md")

MECH_KEY = "mechanism_647_adam_sat_meta_dsa_addictive_design_vs_tiktok_dsa_byline_register_sep11"
TEST_BASENAME = "test_type_b_688_adam_sat_meta_dsa_addictive_design_vs_tiktok_dsa_byline_register_sep11_10pm.py"

META_TONE = -0.50
TIKTOK_TONE = -0.50
EXPECTED_DELTA = 0.0

META_URL = "https://www.techmeme.com/260710/p8"
TIKTOK_URL = "https://techmeme.com/260606/p34"
X_FINE_PROBE_URL = "https://www.techmeme.com/250403/p19"
X_GROK_URL = "https://www.nytimes.com/2026/01/26/business/europeanunionx-grokaiimagesmusk.html"

# Patched in the followup commit per the #565 convention once the main
# commit SHA is known. The rotation-guard class is deselected pre-commit.
ANCHORED_SHA = "placeholder-patched-in-followup-per-565"


def _careers():
    with open(CAREERS_PATH) as f:
        return yaml.safe_load(f)


def _satariano():
    matches = []
    for j in _careers()["journalists"]:
        if isinstance(j, dict) and j.get("name") == "Adam Satariano":
            matches.append(j)
    assert len(matches) == 1, "expected exactly one Adam Satariano entry, got %d" % len(matches)
    return matches[0]


def _mechanism():
    s = _satariano()
    assert MECH_KEY in s, "%s missing from Adam Satariano entry" % MECH_KEY
    return s[MECH_KEY]


def _mechanism_text():
    return yaml.safe_dump(_mechanism(), allow_unicode=True)


def _count_def_tests():
    path = os.path.join(TESTS_DIR, TEST_BASENAME)
    tree = ast.parse(open(path).read())
    return sum(
        isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
        and n.name.startswith("test_")
        for n in ast.walk(tree)
    )


def read_readme():
    with open(README_PATH) as f:
        return f.read()


def read_arch():
    with open(ARCH_PATH) as f:
        return f.read()


def read_log_start():
    with open(LOG_PATH) as f:
        return f.read()


class TestIterationMetadata688:
    def test_iteration_number(self):
        assert _mechanism()["iteration"] == 688

    def test_mechanism_id_next_free(self):
        assert _mechanism()["mechanism_id"] == 647

    def test_mechanism_id_unique_repo_wide(self):
        seen = {}
        for path in glob.glob(os.path.join(REPO_ROOT, "profiles", "**", "*.yaml"), recursive=True):
            text = open(path, encoding="utf-8", errors="replace").read()
            for m in re.finditer(r"mechanism_id:\s*(\d+)", text):
                if int(m.group(1)) == 647:
                    seen.setdefault(647, []).append(path)
        assert len(seen.get(647, [])) == 1, "mechanism_id 647 not unique: %r" % (seen.get(647),)

    def test_type_is_b(self):
        assert _mechanism()["type"] == "B"

    def test_goal_and_job_ids(self):
        m = _mechanism()
        assert m["goal_id"] == "goal_54093bda4145"
        assert m["job_id"] == "mediascope-daily-iteration"
        assert m["scheduled_job_id"] == "mediascope-daily-iteration"

    def test_block_key_matches(self):
        assert _mechanism()["block_key"] == "type_b_688_adam_sat_meta_dsa_addictive_design_vs_tiktok_dsa_byline_register_sep11"

    def test_first_byline_isolated_pair_on_sat(self):
        s = _satariano()
        assert MECH_KEY in s
        other_pairs = [
            k for k in s
            if k.startswith("mechanism_") and k != MECH_KEY
        ]
        assert not other_pairs, "unexpected second mechanism on Adam Satariano: %r" % (other_pairs,)

    def test_no_duplicate_688_file(self):
        others = [
            p for p in glob.glob(os.path.join(TESTS_DIR, "test_type_b_688_*.py"))
            if os.path.basename(p) != TEST_BASENAME
        ]
        assert not others, "duplicate #688 test files: %r" % (others,)


class TestNovelty688:
    """Iteration 688 is new; nothing with this number existed pre-commit."""

    def test_single_type_b_688_file(self):
        matches = glob.glob(os.path.join(REPO_ROOT, "tests", "test_type_b_688*.py"))
        assert len(matches) == 1, "expected exactly this file, got %r" % (matches,)
        assert matches[0].endswith(TEST_BASENAME)

    def test_type_b_688_main_commit_unique_and_anchored(self):
        # Deselected pre-commit per the #565 followup convention; the main
        # commit exists exactly once post-commit and its SHA matches the
        # rotation-guard anchor patched in the followup. Novelty was
        # verified pre-commit by shell greps (zero test_type_b_688 files,
        # no #688 in git log, no mechanism_id 647 in profiles, Meta-arm
        # and Grok-inquiry URLs zero repo-wide hits); this test pins that
        # no duplicate #688 main commit ever appears.
        out = subprocess.run(
            ["git", "log", "--format=%H %s"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        mains = [
            line
            for line in out.stdout.splitlines()
            if re.match(r"^[0-9a-f]{40} Type B #688:", line)
        ]
        assert len(mains) == 1, "expected exactly one Type B #688 main commit, got %r" % (mains,)
        sha = mains[0].split()[0]
        assert sha == TestRotationCycleGuard688.ANCHORED_SHA, (
            "anchor patched in followup per #565 convention"
        )


class TestSatarianoArms688:
    def test_meta_arm_date_and_sole_byline(self):
        meta = _mechanism()["meta_arm"]
        assert meta["date"] == "2026-07-10"
        assert meta["byline"] == "Adam Satariano (sole)"
        assert "full" in meta["byline_attribution"]

    def test_meta_arm_url_verbatim(self):
        assert _mechanism()["meta_arm"]["url"] == META_URL

    def test_meta_arm_url_new_to_corpus_note(self):
        meta = _mechanism()["meta_arm"]
        assert "new to corpus" in meta["byline_attribution"]

    def test_meta_arm_register_and_tone(self):
        meta = _mechanism()["meta_arm"]
        assert "enforcement" in meta["register"]
        assert "addictive design" in meta["register_detail"]
        assert "hefty fines" in meta["register_detail"]
        assert meta["tone_illustrative"] == META_TONE

    def test_meta_arm_evidence_grade_search_attested(self):
        meta = _mechanism()["meta_arm"]
        assert "search-attested" in meta["evidence_grade"]
        assert "policy-blocked" in meta["evidence_grade"]

    def test_tiktok_arm_date_and_sole_byline(self):
        tt = _mechanism()["tiktok_arm"]
        assert tt["date"] == "2026-06-06"
        assert tt["byline"] == "Adam Satariano (sole)"
        assert "full" in tt["byline_attribution"]

    def test_tiktok_arm_url_verbatim(self):
        assert _mechanism()["tiktok_arm"]["url"] == TIKTOK_URL

    def test_tiktok_arm_register_and_tone(self):
        tt = _mechanism()["tiktok_arm"]
        assert "enforcement" in tt["register"]
        assert "addictive design" in tt["register_detail"]
        assert tt["tone_illustrative"] == TIKTOK_TONE

    def test_tiktok_arm_in_corpus_profile_cited(self):
        tt = _mechanism()["tiktok_arm"]
        assert "in-corpus profile citation" in tt["evidence_grade"]

    def test_both_arms_same_publication(self):
        assert _mechanism()["meta_arm"]["date"] == "2026-07-10"
        assert _mechanism()["publication"] == "The New York Times"
        assert "same-journalist" in _mechanism()["pair_shape"]

    def test_same_legal_theory_five_weeks(self):
        tt = _mechanism()["tiktok_arm"]["register_detail"]
        assert "five weeks" in tt

    def test_x_corroboration_arms(self):
        xc = _mechanism()["x_corroboration"]
        assert X_FINE_PROBE_URL in xc["x_fine_probe_arm"]
        assert X_GROK_URL in xc["x_grok_inquiry_arm"]
        assert "1B" in xc["x_fine_probe_arm"]
        assert "Grok" in xc["x_grok_inquiry_arm"]
        assert "120M" in xc["x_grok_inquiry_arm"]
        assert "beat-lens" in xc["corroboration_role"]


class TestScorerDelta688:
    def test_arrays(self):
        s = _mechanism()["asymmetry_scorer_result"]
        assert s["target_tones_manual_illustrative"] == [META_TONE]
        assert s["reference_tones_manual_illustrative"] == [TIKTOK_TONE]

    def test_arithmetic(self):
        s = _mechanism()["asymmetry_scorer_result"]
        delta = s["target_avg"] - s["reference_avg"]
        assert abs(delta - EXPECTED_DELTA) < 1e-9, "delta %r != %r" % (delta, EXPECTED_DELTA)
        assert abs(s["delta_meta_minus_tiktok"] - EXPECTED_DELTA) < 1e-9

    def test_manual_illustrative_guards(self):
        s = _mechanism()["asymmetry_scorer_result"]
        assert s["p_value"] == "NOT_CALCULATED"
        assert s["cohens_d"] == "NOT_CALCULATED"
        assert s["ci"] == "NOT_CALCULATED"
        assert s["is_significant"] is False
        assert s["statistical_contract"] == "degenerate_n1_per_arm"
        assert s["artifact_grade"] is False

    def test_no_engine_run(self):
        s = _mechanism()["asymmetry_scorer_result"]
        assert "no engine run" in s["method"]

    def test_tones_hand_scored_this_run(self):
        s = _mechanism()["asymmetry_scorer_result"]
        assert "hand-assigned" in s["method"]

    def test_limitations_stated(self):
        lim = _mechanism()["asymmetry_scorer_result"]["limitations"]
        assert "no co-byline confound" in lim
        assert "#638/#643" in lim


class TestFinancialContext688:
    def test_correlation_not_causation(self):
        fc = _mechanism()["financial_context"]
        assert "Correlation, not causation" in fc

    def test_nyt_zero_deal_with_all_three_entities(self):
        fc = _mechanism()["financial_context"]
        assert "$0" in fc
        assert "Meta" in fc
        assert "TikTok" in fc
        assert "X" in fc

    def test_vox_openai_contrast(self):
        fc = _mechanism()["financial_context"]
        assert "Vox-OpenAI May 29 2024" in fc

    def test_verdict_bounds(self):
        v = _mechanism()["verdict"]
        assert "SIXTEENTH falsification-family member" in v
        assert "REGISTER CONSTANCY" in v
        assert "near-zero delta" in v
        assert "Correlation, not causation" in v
        assert "No analysis.json update warranted" in v


class TestConfounders688:
    def test_confounders_present_and_ranked(self):
        confs = _mechanism()["confounders"]
        assert len(confs) >= 6
        assert sum(c.startswith("[STRONG]") for c in confs) >= 3

    def test_strong_excerpt_bounded(self):
        confs = _mechanism()["confounders"]
        strong = [c for c in confs if c.startswith("[STRONG]")]
        assert any("Excerpt-bounded" in c for c in strong)

    def test_strong_event_driven_genre(self):
        confs = _mechanism()["confounders"]
        strong = [c for c in confs if c.startswith("[STRONG]")]
        assert any("Event-driven genre" in c for c in strong)

    def test_strong_same_legal_theory(self):
        confs = _mechanism()["confounders"]
        strong = [c for c in confs if c.startswith("[STRONG]")]
        assert any("Same-legal-theory" in c for c in strong)

    def test_moderate_time_order(self):
        confs = _mechanism()["confounders"]
        mod = [c for c in confs if c.startswith("[MODERATE]")]
        assert any("Time order" in c for c in mod)

    def test_cross_references_constancy_family(self):
        refs = " ".join(_mechanism()["cross_references"])
        assert "#477/#482/#488/#493/#498/#508/#513/#518" in refs
        assert "#672/#678" in refs
        assert "#646/#682" in refs

    def test_novelty_language(self):
        nov = _mechanism()["novelty"]
        assert "FIRST dedicated Type B on Adam Satariano" in nov
        assert "zero mechanism_* keys pre-existing" in nov


class TestRotationCycleGuard688:
    # Deselected pre-commit per the #565 followup convention; the rotation
    # window only closes once the #688 main commit exists.
    ANCHORED_SHA = ANCHORED_SHA

    @staticmethod
    def _mains():
        out = subprocess.run(
            ["git", "log", "--format=%s"],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            check=True,
        ).stdout.splitlines()
        return [s for s in out if re.match(r"^Type [A-E] #\d+:", s)]

    def test_window_684_688_closes_a_to_b(self):
        subjects = self._mains()
        observed = []
        for s in subjects[:5]:
            m = re.search(r"Type ([A-E]) #(\d+):", s)
            assert m, "unparseable rotation subject: %r" % (s,)
            observed.append((m.group(1), m.group(2)))
        assert observed == [
            ("B", "688"),
            ("A", "687"),
            ("E", "686"),
            ("D", "685"),
            ("C", "684"),
        ], "rotation window 684-688 wrong: %r" % (observed,)

    def test_rotation_adjacency_cycle_valid(self):
        subjects = self._mains()
        observed = []
        for s in subjects[:5]:
            m = re.search(r"Type ([A-E]) #(\d+):", s)
            assert m
            observed.append(m.group(1))
        assert observed == ["B", "A", "E", "D", "C"]
        order = {"A": 0, "B": 1, "C": 2, "D": 3, "E": 4}
        for a, b in zip(observed, observed[1:]):
            assert (order[a] - order[b]) % 5 == 1, (
                "rotation broken: %s -> %s is not a valid cycle edge" % (a, b)
            )

    def test_anchor_is_main_patch_in_followup(self):
        # Post-commit anchor: the #688 main commit. Patched in the followup
        # per the #565 convention once the main commit SHA is known.
        pytest.skip("anchor patched in followup per #565 convention")

    def test_rotation_guard_regex_actually_matches(self):
        # #632 process note: a rotation guard whose regex never matches is a
        # silent no-op. Verify the guard regexes match a real main-commit
        # subject (the double-backslash r"...#(\d+)..." form silently matches
        # nothing). Written as a semantic check rather than a literal-pattern
        # check so the test cannot defeat itself by containing the pattern.
        src = open(os.path.join(TESTS_DIR, TEST_BASENAME)).read()
        patterns = re.findall(r're\.search\(r"([^"]+)"', src)
        guard_patterns = [p for p in patterns if p.startswith("Type (")]
        assert guard_patterns, "no rotation-guard regex found in this file"
        sample = "Type B #688: Adam Satariano Meta DSA addictive design vs TikTok DSA byline register"
        for p in guard_patterns:
            m = re.search(p, sample)
            assert m and m.group(1) == "B" and m.group(2) == "688", (
                "rotation regex %r fails to match a real subject "
                "(double-backslash bug?)" % (p,)
            )


class TestDocSyncRatchet688:
    # Fails pre-commit by design per the #565 followup convention; the README
    # test-file table row and ARCHITECTURE tree row land in the doc-sync commit.
    def test_readme_has_688_row(self):
        assert "test_type_b_688" in read_readme()

    def test_arch_has_688_row(self):
        assert "test_type_b_688" in read_arch()

    def test_readme_row_mentions_sat(self):
        assert "Adam Satariano" in read_readme()

    def test_log_starts_with_688(self):
        assert read_log_start().startswith("#688 Type B:")

    def test_def_test_count_matches(self):
        # The README row for #688 must carry this file's own def-test count.
        n = _count_def_tests()
        assert str(n) in read_readme(), (
            "README #688 row should mention this file's def-test count %d" % n
        )


class TestNoBrittlePatterns688:
    def test_yaml_reparses_clean(self):
        s = _satariano()
        m = s[MECH_KEY]
        assert isinstance(m["mechanism_id"], int)
        assert isinstance(m["meta_arm"]["tone_illustrative"], float)
        assert isinstance(m["tiktok_arm"]["tone_illustrative"], float)
        assert isinstance(m["asymmetry_scorer_result"]["is_significant"], bool)

    def test_no_em_dash_in_mechanism(self):
        assert "\u2014" not in _mechanism_text()
        assert "\u2028" not in _mechanism_text()
        src = open(os.path.join(TESTS_DIR, TEST_BASENAME)).read()
        assert "\u2014" not in src
        assert "\u2028" not in src

    def test_all_urls_http_or_https(self):
        urls = [
            _mechanism()["meta_arm"]["url"],
            _mechanism()["tiktok_arm"]["url"],
        ]
        assert urls, "no URLs recorded"
        for u in urls:
            assert u.startswith(("http://", "https://")), "bad URL: %r" % (u,)
