"""Tests for worker_replacement_irony and two_tier_treatment framing patterns.

Based on WebProNews Meta Dublin contractors article (May 29, 2026):
"Meta Contractors Fight for Scraps as AI Replaces Dublin Content Moderators"

Tests the two new framing device patterns:
- worker_replacement_irony: workers build/train AI that replaces them
- two_tier_treatment: explicit comparison of different employee class treatment
"""

import pytest

from mediascope.analyze.framing import detect_framing_devices


# ---------------------------------------------------------------------------
# worker_replacement_irony
# ---------------------------------------------------------------------------


class TestWorkerReplacementIrony:
    """Worker replacement irony: trained the AI that replaced them."""

    def test_forward_trained_ai_replaced(self):
        """Forward form: trained AI models → face replacement."""
        text = (
            "Content moderators who trained AI models now face "
            "replacement by those same systems, with many receiving "
            "no payout at all."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "worker_replacement_irony" in types

    def test_reverse_replacements_are_models_they_built(self):
        """Reverse form: replacements are the very models they helped build."""
        text = (
            "Their replacements are the very models they helped build. "
            "The irony is not lost on the workers."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "worker_replacement_irony" in types

    def test_chant_form(self):
        """Chant/slogan form: We trained the bots... left behind."""
        text = (
            "We trained the bots. We did the grind. "
            "Now we're being left behind."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "worker_replacement_irony" in types

    def test_labeled_data_then_laid_off(self):
        """Workers who labeled data for AI models face layoffs."""
        text = (
            "Employees annotated data to train the company's AI models. "
            "They reviewed material generated by those models for illicit "
            "content. Now those same workers have been laid off as the "
            "models handle moderation autonomously."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "worker_replacement_irony" in types

    def test_no_fire_on_generic_layoffs(self):
        """Should not fire on generic layoff language without AI training."""
        text = (
            "The company announced 500 layoffs across its Dublin office "
            "as part of a broader restructuring plan. Workers received "
            "standard severance packages."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "worker_replacement_irony" not in types

    def test_no_fire_on_generic_ai_adoption(self):
        """Should not fire on AI adoption without worker-built-it angle."""
        text = (
            "The company adopted AI-powered content moderation tools, "
            "reducing the need for human reviewers. The new system uses "
            "advanced machine learning models to detect violations."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "worker_replacement_irony" not in types


# ---------------------------------------------------------------------------
# two_tier_treatment
# ---------------------------------------------------------------------------


class TestTwoTierTreatment:
    """Two-tier treatment: different classes, different treatment."""

    def test_denied_privileges_of_staff(self):
        """Classic form: denied all the privileges of company staff."""
        text = (
            "They're constantly using Meta tools, they're on Meta "
            "platforms. But they're denied all the privileges and "
            "benefits of Meta staff."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "two_tier_treatment" in types

    def test_full_time_vs_contractor_severance(self):
        """Explicit comparison of full-time vs contractor severance."""
        text = (
            "Full-time employees reportedly stand to receive four "
            "months' pay plus two weeks for every year served. "
            "Outsourced workers at the contracting firm get far less."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "two_tier_treatment" in types

    def test_not_even_employees(self):
        """Using company tools/platforms but not company employees."""
        text = (
            "Workers who spend every day using Meta's tools and "
            "working on Meta's platforms are not actually employees "
            "of the company. They have no access to the benefits "
            "that Meta staff enjoy."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "two_tier_treatment" in types

    def test_no_fire_on_generic_layoffs(self):
        """Should not fire on single-class layoff language."""
        text = (
            "The company laid off 300 employees last quarter as "
            "part of a cost-reduction initiative. All affected "
            "workers received standard severance packages."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "two_tier_treatment" not in types


# ---------------------------------------------------------------------------
# geopolitical_regulatory_pressure false positive fix
# ---------------------------------------------------------------------------


class TestGeopoliticalFalsePositiveFix:
    """Ensure 'stood firm' in physical contexts doesn't fire."""

    def test_security_guards_stood_firm_no_fire(self):
        """Physical 'stood firm' by security guards is not geopolitical."""
        text = (
            "The security guards at Meta's gates stood firm, arms "
            "crossed, as protesters chanted outside."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "geopolitical_regulatory_pressure" not in types

    def test_police_stood_firm_no_fire(self):
        """Physical 'stood firm' by police is not geopolitical."""
        text = (
            "Police officers stood firm at the barricade while "
            "demonstrators shouted slogans."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "geopolitical_regulatory_pressure" not in types

    def test_government_stood_firm_still_fires(self):
        """Geopolitical 'stood firm' by a government should still fire."""
        text = (
            "The EU Commission stood firm on its antitrust ruling "
            "despite pressure from American tech giants."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "geopolitical_regulatory_pressure" in types


# ---------------------------------------------------------------------------
# outsourced_intensity expansion
# ---------------------------------------------------------------------------


class TestOutsourcedIntensityExpansion:
    """Expanded outsourced intensity for labor-context expert quotes."""

    def test_professor_open_season(self):
        """Expert 'open season' quote should fire."""
        text = (
            "Michael Doherty, a labor law professor at Maynooth "
            'University, described Irish rules as leaving employers '
            'with wide latitude. "It\'s pretty much open season."'
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "outsourced_intensity" in types

    def test_professor_cynical_quote(self):
        """Expert 'cynical' quote should fire."""
        text = (
            '"Call me cynical, but I don\'t believe much in morals '
            'when it comes to labor rights," said Doherty, a professor '
            "at Maynooth University."
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "outsourced_intensity" in types

    def test_professor_utter_inability(self):
        """Expert 'utter inability' quote should fire."""
        text = (
            "Doherty, a labor law professor at Maynooth University, "
            'described the situation: "The big weakness in Ireland '
            "is this utter inability even to get the employer to sit "
            'down."'
        )
        devices = detect_framing_devices(text)
        types = {d.device_type for d in devices}
        assert "outsourced_intensity" in types
