"""Weekly report generator for MediaScope analysis.

Produces a Markdown report covering coverage volume, sentiment asymmetry,
journalist breakdown, framing devices, and conflict disclosures.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from datetime import datetime
from typing import Optional

try:
    from jinja2 import Template
except ImportError:
    Template = None  # type: ignore[assignment, misc]

from mediascope.score.asymmetry import generate_asymmetry_report
from mediascope.score.byline import build_journalist_profiles, rank_by_asymmetry
from mediascope.quality.standards import check_quality


_WEEKLY_TEMPLATE = """\
# MediaScope Weekly Report
**Publication:** {{ publication_slug }}
**Target Entity:** {{ target_entity }}
**Period:** {{ period_start }} – {{ period_end }}
**Generated:** {{ generated_at }}

---

## Executive Summary

{{ executive_summary }}

---

## Coverage Volume

- **Total articles analyzed:** {{ total_articles }}
- **Articles mentioning {{ target_entity }}:** {{ target_articles }}
- **Articles mentioning peer entities:** {{ peer_articles }}
- **Target coverage share:** {{ target_share }}%

---

## Sentiment Asymmetry Scores

| Entity | Avg Tone | Articles | Asymmetry | p-value | Cohen's d | Significant? |
|--------|----------|----------|-----------|---------|-----------|-------------|
{% for entity, score in asymmetry_rows %}\
| {{ entity }} | {{ "%.3f"|format(score.target_avg_tone) }} vs {{ "%.3f"|format(score.peer_avg_tone) }} | {{ score.article_count_target }} vs {{ score.article_count_peers }} | {{ "%.3f"|format(score.asymmetry_score) }} | {{ "%.4f"|format(score.p_value) }} | {{ "%.2f"|format(score.cohens_d) }} | {{ "Yes ⚠️" if score.is_significant else "No" }} |
{% endfor %}
**Overall asymmetry score:** {{ "%.3f"|format(overall_asymmetry) }}

---

## Top Articles by Bias Score

{% for article in top_articles %}\
{{ loop.index }}. **{{ article.title }}** ({{ article.date }})
   - Tone: {{ "%.2f"|format(article.tone) }} | Author: {{ article.author }}
   {% if article.url %}- URL: {{ article.url }}{% endif %}

{% endfor %}

---

## Journalist Breakdown

| Journalist | Articles | Asymmetry vs Peers | Anon Source Avg | Speculative Lang |
|-----------|----------|-------------------|-----------------|-----------------|
{% for name, asym in journalist_rankings[:15] %}\
| {{ name }} | {{ journalist_profiles[name].article_count }} | {{ "%.3f"|format(asym) }} | {{ "%.1f"|format(journalist_profiles[name].anonymous_source_avg * 100) }}% | {{ "%.1f"|format(journalist_profiles[name].speculative_language_avg * 100) }}% |
{% endfor %}

---

## Framing Devices Used

{% for device, count in framing_devices[:20] %}\
- **{{ device }}**: {{ count }} occurrences
{% endfor %}

---

## Conflict Disclosure

{{ disclosure_text }}

---

## Methodology Note

{{ methodology_note }}

---

## Limitations

- Sentiment scores are LLM-generated and should be treated as relative, not absolute.
- Entity matching may miss aliases or subsidiaries not in the canonical name map.
- Coverage volume may not reflect all published articles if scraping coverage is incomplete.
- Asymmetry scores require a minimum of 2 articles per entity for statistical validity.
- This report does not assess factual accuracy of the articles themselves.

---

*Generated by MediaScope v0.1.0*
"""


def generate_weekly_report(
    articles: list[dict],
    publication_slug: str,
    target_entity: str,
    period_start: datetime,
    period_end: datetime,
) -> str:
    """Generate a weekly Markdown report from analyzed articles.

    Each article dict should have:
        - "title" (str)
        - "url" (str, optional)
        - "author" (str)
        - "published_date" (str or datetime)
        - "entities" (list[str])
        - "sentiment" (dict with "overall_tone": float)
        - "anonymous_source_ratio" (float, optional)
        - "speculative_language_ratio" (float, optional)
        - "framing_devices" (list[str], optional)

    Args:
        articles: Analyzed articles.
        publication_slug: Publication identifier.
        target_entity: Entity under analysis.
        period_start: Report period start.
        period_end: Report period end.

    Returns:
        Markdown-formatted report string.
    """
    target_lower = target_entity.lower()

    # ── Asymmetry ────────────────────────────────────────────────────
    report = generate_asymmetry_report(
        articles, publication_slug, target_entity, period_start, period_end,
    )
    asymmetry_rows = sorted(
        report.scores_by_entity.items(),
        key=lambda x: x[1].asymmetry_score,
    )

    # ── Journalist profiles ──────────────────────────────────────────
    profiles = build_journalist_profiles(articles)
    rankings = rank_by_asymmetry(profiles, target_entity)

    # ── Coverage counts ──────────────────────────────────────────────
    target_articles = sum(
        1 for a in articles
        if any(e.lower() == target_lower for e in a.get("entities", []))
    )
    peer_articles = len(articles) - target_articles
    target_share = round(target_articles / len(articles) * 100, 1) if articles else 0

    # ── Top articles by tone ─────────────────────────────────────────
    scored_articles = []
    for a in articles:
        tone = a.get("sentiment", {}).get("overall_tone")
        if tone is not None and any(
            e.lower() == target_lower for e in a.get("entities", [])
        ):
            scored_articles.append({
                "title": a.get("title", "Untitled"),
                "url": a.get("url", ""),
                "author": a.get("author", "Unknown"),
                "date": str(a.get("published_date", ""))[:10],
                "tone": float(tone),
            })
    scored_articles.sort(key=lambda x: x["tone"])
    top_articles = scored_articles[:10]

    # ── Framing devices ──────────────────────────────────────────────
    device_counter: Counter[str] = Counter()
    for a in articles:
        for device in a.get("framing_devices", []):
            device_counter[device] += 1
    framing_devices = device_counter.most_common(20)

    # ── Executive summary ────────────────────────────────────────────
    direction = "more negative" if report.overall_asymmetry < 0 else "more positive"
    exec_summary = (
        f"During {period_start.strftime('%b %d')}–{period_end.strftime('%b %d, %Y')}, "
        f"**{publication_slug}** published {len(articles)} articles analyzed by MediaScope. "
        f"Coverage of **{target_entity}** was {direction} than peer entities by "
        f"{abs(report.overall_asymmetry):.3f} points on the sentiment scale. "
    )
    if report.most_negative_entity:
        exec_summary += (
            f"The entity with the largest negative asymmetry was "
            f"**{report.most_negative_entity}** "
            f"(Δ = {report.scores_by_entity.get(report.most_negative_entity, type('', (), {'asymmetry_score': 0})).asymmetry_score:.3f}). "
        )
    if rankings:
        exec_summary += (
            f"The journalist with the most asymmetric coverage was "
            f"**{rankings[0][0]}** (asymmetry: {rankings[0][1]:.3f})."
        )

    # ── Render ───────────────────────────────────────────────────────
    context = {
        "publication_slug": publication_slug,
        "target_entity": target_entity,
        "period_start": period_start.strftime("%Y-%m-%d"),
        "period_end": period_end.strftime("%Y-%m-%d"),
        "generated_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        "executive_summary": exec_summary,
        "total_articles": len(articles),
        "target_articles": target_articles,
        "peer_articles": peer_articles,
        "target_share": target_share,
        "asymmetry_rows": asymmetry_rows,
        "overall_asymmetry": report.overall_asymmetry,
        "top_articles": top_articles,
        "journalist_rankings": rankings,
        "journalist_profiles": profiles,
        "framing_devices": framing_devices,
        "disclosure_text": "See conflicts/disclosure module for full disclosure.",
        "methodology_note": report.methodology_note,
    }

    if Template is not None:
        tpl = Template(_WEEKLY_TEMPLATE)
        return tpl.render(**context)

    # Fallback: simple string assembly
    return _fallback_report(context)


def _fallback_report(ctx: dict) -> str:
    """Minimal report when Jinja2 is unavailable."""
    lines = [
        f"# MediaScope Weekly Report",
        f"**Publication:** {ctx['publication_slug']}",
        f"**Target Entity:** {ctx['target_entity']}",
        f"**Period:** {ctx['period_start']} – {ctx['period_end']}",
        f"**Generated:** {ctx['generated_at']}",
        "",
        "## Executive Summary",
        ctx["executive_summary"],
        "",
        f"## Coverage Volume",
        f"- Total articles: {ctx['total_articles']}",
        f"- Target articles: {ctx['target_articles']}",
        f"- Peer articles: {ctx['peer_articles']}",
        f"- Target share: {ctx['target_share']}%",
        "",
        f"## Overall Asymmetry: {ctx['overall_asymmetry']:.3f}",
        "",
        "Install Jinja2 for the full formatted report.",
    ]
    return "\n".join(lines)
