"""Disclosure statement generator for media conflict-of-interest reporting.

Generates full-length, social-media, and machine-readable disclosures
from publication profiles using Jinja2 templates.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

try:
    from jinja2 import Template
except ImportError:
    # Fallback: lightweight string formatting if Jinja2 not installed
    Template = None  # type: ignore[assignment, misc]

from mediascope.conflicts.ownership import (
    OwnershipChain,
    format_ownership_text,
    find_conflicts,
    parse_ownership_chain,
)
from mediascope.conflicts.revenue import (
    RevenueRelationship,
    calculate_financial_exposure,
    find_revenue_conflicts,
    load_revenue_data,
)
from mediascope.conflicts.litigation import (
    find_media_litigation_links,
    format_litigation_network,
    load_litigation_data,
)

__version__ = "0.1.0"

# ── Jinja2 template for full disclosure ──────────────────────────────
_FULL_DISCLOSURE_TEMPLATE = """\
CONFLICT OF INTEREST DISCLOSURE
Publication: {{ publication_name }}
{% if article_url %}Article: {{ article_url }}
{% endif %}Date Generated: {{ date_generated }}

OWNERSHIP CHAIN:
{{ ownership_text }}

FINANCIAL CONFLICTS:
{% if conflicts %}{% for c in conflicts %}{{ loop.index }}. [Severity {{ c.severity }}/5] {{ c.description }}
   Type: {{ c.conflict_type }}
   Source: {{ c.source_entity }}
   {% if c.source_url %}Reference: {{ c.source_url }}
   {% endif %}
{% endfor %}{% else %}No financial conflicts identified.
{% endif %}

COMPETITIVE RELATIONSHIPS:
{% if revenue_conflicts %}{% for r in revenue_conflicts %}- {{ r.partner }} ({{ r.relationship_type }}{% if r.estimated_value %}, est. ${{ "{:,.0f}".format(r.estimated_value) }}{% endif %}): {{ r.description }}
{% endfor %}{% else %}No competitive revenue relationships identified.
{% endif %}

LITIGATION CONNECTIONS:
{% if litigation_links %}{% for link in litigation_links %}- {{ link.description }}
  Cases affected: {{ link.cases_affected | join(', ') if link.cases_affected else 'None identified' }}
{% endfor %}{% else %}No litigation connections identified.
{% endif %}

METHODOLOGY: This disclosure was generated by MediaScope v{{ version }} using \
structured publication profile data. Ownership chains are sourced from SEC filings, \
corporate registries, and public records. Financial relationships are estimated from \
public reporting and may not reflect current arrangements. Litigation data is sourced \
from court records and TPLF registries. This disclosure is informational and does not \
constitute legal advice.
"""

_SOCIAL_TEMPLATE_SHORT = (
    "⚠️ Disclosure: {{ publication_name }} is owned by {{ ultimate_parent }}. "
    "{% if top_conflict %}Key conflict: {{ top_conflict }}{% endif %} "
    "#MediaScope"
)

_SOCIAL_TEMPLATE_LONG = (
    "⚠️ Conflict of Interest Disclosure\n\n"
    "{{ publication_name }} is owned by {{ ultimate_parent }}.\n\n"
    "{% if conflicts %}Key conflicts:\n"
    "{% for c in conflicts[:3] %}"
    "• {{ c.description }}\n"
    "{% endfor %}"
    "{% endif %}"
    "\n{% if revenue_total %}Financial exposure: ${{ \"{:,.0f}\".format(revenue_total) }}\n{% endif %}"
    "\nGenerated by MediaScope v{{ version }}"
)


def _render(template_str: str, context: dict) -> str:
    """Render a template string with the given context."""
    if Template is not None:
        tpl = Template(template_str)
        return tpl.render(**context)
    # Minimal fallback — simple str.format won't handle Jinja2 syntax,
    # so just return a plaintext summary
    return f"Disclosure for {context.get('publication_name', 'unknown')} — install Jinja2 for full output."


def _build_context(
    profile,
    target_entity: str,
    article_url: Optional[str] = None,
) -> dict:
    """Build the shared template context from a profile.

    Accepts both raw YAML dicts and PublicationProfile objects.
    """
    publication_name = getattr(profile, "name", None) or (
        profile.get("name", profile.get("slug", "Unknown Publication"))
        if isinstance(profile, dict) else "Unknown Publication"
    )
    chain = parse_ownership_chain(profile)
    ownership_text = format_ownership_text(chain)

    entity_data = profile.get("entity_data", {})
    conflicts = find_conflicts(chain, target_entity, entity_data)

    revenue_rels = load_revenue_data(profile)
    revenue_conflicts = find_revenue_conflicts(revenue_rels, target_entity)
    exposure = calculate_financial_exposure(revenue_conflicts)

    funders, cases = load_litigation_data(profile)
    litigation_links = find_media_litigation_links(funders, cases, chain)

    return {
        "publication_name": publication_name,
        "article_url": article_url,
        "date_generated": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "ownership_text": ownership_text,
        "conflicts": conflicts,
        "revenue_conflicts": revenue_conflicts,
        "revenue_total": exposure.get("total", 0),
        "litigation_links": litigation_links,
        "ultimate_parent": chain.ultimate_parent or "Unknown",
        "top_conflict": conflicts[0].description if conflicts else "",
        "version": __version__,
    }


def generate_disclosure(
    profile,
    target_entity: str,
    article_url: str | None = None,
) -> str:
    """Generate a complete conflict-of-interest disclosure statement.

    Args:
        profile: Publication profile (PublicationProfile or raw dict).
        target_entity: The entity whose coverage may be conflicted.
        article_url: Optional URL of the specific article.

    Returns:
        Full disclosure text.
    """
    ctx = _build_context(profile, target_entity, article_url)
    return _render(_FULL_DISCLOSURE_TEMPLATE, ctx)


def generate_social_disclosure(
    profile,
    target_entity: str,
) -> str:
    """Generate a shorter disclosure suitable for social media.

    Returns a short version (≤ 280 chars for X/Twitter) and appends a
    longer version separated by a blank line if the short version is
    insufficient.

    Args:
        profile: Publication profile (PublicationProfile or raw dict).
        target_entity: Target entity.

    Returns:
        Social-ready disclosure text.
    """
    ctx = _build_context(profile, target_entity)

    short = _render(_SOCIAL_TEMPLATE_SHORT, ctx).strip()
    if len(short) > 280:
        # Truncate for X/Twitter
        short = short[:277] + "..."

    long_version = _render(_SOCIAL_TEMPLATE_LONG, ctx).strip()

    return f"{short}\n\n---\n\n{long_version}"


def generate_disclosure_json(
    profile,
    target_entity: str,
) -> dict:
    """Generate a machine-readable disclosure as a dictionary.

    Args:
        profile: Publication profile dict.
        target_entity: Target entity.

    Returns:
        Dict with structured disclosure data.
    """
    ctx = _build_context(profile, target_entity)

    return {
        "version": __version__,
        "generated_at": ctx["date_generated"],
        "publication": ctx["publication_name"],
        "target_entity": target_entity,
        "ownership": {
            "ultimate_parent": ctx["ultimate_parent"],
            "chain_text": ctx["ownership_text"],
        },
        "conflicts": [
            {
                "type": c.conflict_type,
                "source": c.source_entity,
                "target": c.target_entity,
                "description": c.description,
                "severity": c.severity,
                "evidence": c.evidence,
                "source_url": c.source_url,
            }
            for c in ctx["conflicts"]
        ],
        "revenue_conflicts": [
            {
                "partner": r.partner,
                "type": r.relationship_type,
                "value": r.estimated_value,
                "description": r.description,
            }
            for r in ctx["revenue_conflicts"]
        ],
        "litigation_links": ctx["litigation_links"],
        "total_financial_exposure": ctx["revenue_total"],
        "methodology": (
            f"Generated by MediaScope v{__version__}. Ownership from SEC/public records. "
            "Financial relationships estimated from public reporting."
        ),
    }
